version: '3'

services:
  oracledb:
    build:
      context: ./18c-xe
    container_name: oracledb
    ports:
      - '1521:1521'
      - '35518:5500'
    volumes:
      - ~/docker-services/oracle/18c-xe:/opt/oracle/oradata
    environment:
      - ORACLE_PASSWORD=mypassword
    networks:
      - oracle_network

networks:
  oracle_network: {}